Resources:
  isaVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.2.0.0/16
      Tags:
        - Key: Name
          Value: isaVPC
  isaCF:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Used for Ec2 Instance Connect and SSH
      GroupName: isaCF
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: isaCF
      VpcId:
        Ref: isaVPC
  myInternetGatewayCF:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: myInternetGatewayCF
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref myRouteTableCF
      SubnetId: !Ref Subnet
  myInternetGatewayCFAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId:
        Ref: myInternetGatewayCF
      VpcId:
        Ref: isaVPC
  myRouteTableCF:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      Tags:
        - Key: Name
          Value: myRouteTableCF
      VpcId:
        Ref: isaVPC
  IGWRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: myInternetGatewayCF
      RouteTableId:
        Ref: myRouteTableCF
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.2.1.0/24
      Tags:
        - Key: Name
          Value: Subnet
      VpcId:
        Ref: isaVPC
  isaEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-047a51fa27710816e
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId:
            Ref: Subnet
          DeleteOnTermination: true
          GroupSet:
            - Ref: isaCF
      Tags:
        - Key: Name
          Value: isaEC2b
  isaEC22:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-047a51fa27710816e
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId:
            Ref: Subnet
          DeleteOnTermination: true
          GroupSet:
            - Ref: isaCF
      Tags:
        - Key: Name
          Value: isaEC22b